name: Execução de Testes API Rest

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_SENHA: ${{ secrets.ADMIN_SENHA }}
      FABIO_EMAIL: ${{ secrets.FABIO_EMAIL }}
      FABIO_SENHA: ${{ secrets.FABIO_SENHA }}

    steps: 
    - name: fazer checkout do repositório
      uses: actions/checkout@v4

    - name: Definir versão do node.jobs
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"

    - name: Instalar Dependências
      run: npm install

    - name: Iniciar API
      run: npm start &

    - name: Aguardar a API Iniciar
      run: sleep 5

    - name: Executar o Teste
      run: npm test